  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=docker_user
        - POSTGRES_PASSWORD=insecure_password
      ports:
        - "8001:5432"
    web:
      build: .
      command: sh /code/runserver.sh
      volumes:
        - .:/code
      ports:
        - "64646:64646"
      depends_on:
        - db
