# Generated by Django 3.0.8 on 2020-08-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='/static/404.jpg', upload_to='posts'),
        ),
    ]
